### ISSUE TITLE
Bug for non-square input tensor

### ISSUE THREAD

**Issue by JMingKuo** [mkocabas/CoordConv-pytorch#1]
There is a bug in the original implementation as they using x_dim to tile the x_range tensor.
It will result in xx_channel with shape [x_dim, x_dim] and yy_channel with shape [y_dim, y_dim]
and then the concatenate is not allowed for non-square case.

Please refer to correct implementation as
https://gist.github.com/leVirve/0377a8fbac455bfd44e374e5cf8b1260

**Comment by mkocabas** [comment]
Thanks for the correction @JMingKuo ! May I update the code according to your implementation?

**Comment by JMingKuo** [comment]
That link is not mine, maybe you should ask the repo owner @leVirve and I think he would will to that.

**Comment by mkocabas** [comment]
Oh, I see. Let me ask @leVirve then.

**Comment by mkocabas** [comment]
Issue has been solved. Thanks for pointing out @JMingKuo!

**Comment by JMingKuo** [comment]
I just found another bug comes with the previous one.

The code below:
xx_channel = xx_channel.float() / (self.x_dim - 1)
yy_channel = yy_channel.float() / (self.y_dim - 1)

should be
xx_channel = xx_channel.float() / (self.**y_dim** - 1)
yy_channel = yy_channel.float() / (self.**x_dim** - 1)

as the dimension of each x is y rather than x.
