### ISSUE TITLE
channel errors

### ISSUE THREAD

**Issue by PYsaber** [mkocabas/CoordConv-pytorch#8]
Hello,
At the code,
https://github.com/mkocabas/CoordConv-pytorch/blob/d833f1e978879e9f655977085191094958a5916b/CoordConv.py#L115

if `with_r == True`,this should be in_channels + 3 instead of in_channels + 2

**Comment by mkocabas** [comment]
Yes @PYsaber, you're right. I've fixed the problem in this [commit](https://github.com/mkocabas/CoordConv-pytorch/commit/7081f3dd740dcdb049dec7b84d27065fa8ddeacb).

Thanks for reporting the bug.
